import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href='/'>HOME</Link>
          <Link href='/test'>TEST</Link>
          <Link href='/js'>Js</Link>
        </header>

        <Context>
          <main>{children}</main>
        </Context>
        
        <footer>@test.com</footer>
        </body>
    </html>
  )
}
